import { healthcheckHandler } from './healthcheck.js';
import { cacheConnection } from './checks/cache.js';
import { cpuCheck } from './checks/cpu.js';
import { dbConnection } from './checks/db.js';
import { disk } from './checks/disk.js';
import { egress } from './checks/egress.js';
import { memoryCheck } from './checks/memory.js';
import { Status, type Config } from './index.js';

jest.mock('./checks/cache.js', () => ({
  cacheConnection: jest.fn(),
}));

jest.mock('./checks/cpu.js', () => ({
  cpuCheck: jest.fn(),
}));

jest.mock('./checks/db.js', () => ({
  dbConnection: jest.fn(),
}));

jest.mock('./checks/disk.js', () => ({
  disk: jest.fn(),
}));

jest.mock('./checks/egress.js', () => ({
  egress: jest.fn(),
}));

jest.mock('./checks/memory.js', () => ({
  memoryCheck: jest.fn(),
}));

describe('healthcheckHandler', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  const buildConfig = (checks: Record<string, boolean>): Config => ({
    checks,
  } as unknown as Config);

  it('should return a passing JSON response when all enabled checks pass', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    (cpuCheck as jest.Mock).mockResolvedValue({
      componentName: 'cpu_usage',
      status: Status.pass,
      message: 'CPU usage is below 80%',
      value: '20.00%',
      time: 3,
    });

    const config = buildConfig({
      memory_usage: true,
      cpu_usage: true,
    });

    const result = await healthcheckHandler({}, config);

    expect(result.type).toBe('application/json');
    const parsed = JSON.parse(result.body);

    expect(parsed.status).toBe(Status.pass);
    expect(parsed.description).toBe('Health check response, generated by allgood.');
    expect(parsed.results).toEqual({
      memory_usage: {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below threshold',
        value: '50%',
        time: 5,
      },
      cpu_usage: {
        componentName: 'cpu_usage',
        status: Status.pass,
        message: 'CPU usage is below 80%',
        value: '20.00%',
        time: 3,
      },
    });

    expect(memoryCheck).toHaveBeenCalledWith(config);
    expect(cpuCheck).toHaveBeenCalledWith(config);
  });

  it('should not run checks that are disabled in config', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    const config = buildConfig({
      memory_usage: true,
      cpu_usage: false,
    });

    const result = await healthcheckHandler({}, config);
    const parsed = JSON.parse(result.body);

    expect(parsed.results).toEqual({
      memory_usage: {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below threshold',
        value: '50%',
        time: 5,
      },
    });

    expect(cpuCheck).not.toHaveBeenCalled();
  });

  it('should ignore check names that are not registered in checks registry', async () => {
    const config = buildConfig({
      unknown_check: true,
    });

    const result = await healthcheckHandler({}, config);
    const parsed = JSON.parse(result.body);

    expect(parsed.status).toBe(Status.pass);
    expect(parsed.results).toEqual({});
  });

  it('should return warn status if any check returns warn', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    (diskWarnMock());

    function diskWarnMock() {
      (disk as jest.Mock).mockResolvedValue({
        componentName: 'disk_space',
        status: Status.warn,
        message: 'Disk space is running low',
        value: '85%',
        time: 4,
      });
    }

    const config = buildConfig({
      memory_usage: true,
      disk_space: true,
    });

    const result = await healthcheckHandler({}, config);
    const parsed = JSON.parse(result.body);

    expect(parsed.status).toBe(Status.warn);
  });

  it('should return fail status if any check returns fail', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    (dbConnection as jest.Mock).mockResolvedValue({
      componentName: 'db_connection',
      status: Status.fail,
      message: 'Database connection failed',
      value: 'false',
      time: 2,
    });

    const config = buildConfig({
      memory_usage: true,
      db_connection: true,
    });

    const result = await healthcheckHandler({}, config);
    const parsed = JSON.parse(result.body);

    expect(parsed.status).toBe(Status.fail);
  });

  it('should prioritize fail over warn when both are present depending on execution order', async () => {
    (egress as jest.Mock).mockResolvedValue({
      componentName: 'outbound_internet',
      status: Status.warn,
      message: 'Slow outbound connection',
      value: 'true',
      time: 10,
    });

    (dbConnection as jest.Mock).mockResolvedValue({
      componentName: 'db_connection',
      status: Status.fail,
      message: 'Database connection failed',
      value: 'false',
      time: 2,
    });

    const config = buildConfig({
      outbound_internet: true,
      db_connection: true,
    });

    const result = await healthcheckHandler({}, config);
    const parsed = JSON.parse(result.body);

    // Since status is set based on whichever finishes last among fail/warn checks,
    // we just confirm it's not pass and one of fail/warn.
    expect([Status.fail, Status.warn]).toContain(parsed.status);
  });

  it('should return HTML response when Accept header includes text/html', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    const config = buildConfig({
      memory_usage: true,
    });

    const result = await healthcheckHandler({ accept: 'text/html' }, config);

    expect(result.type).toBe('text/html');
    expect(result.body).toContain('<!DOCTYPE html>');
    expect(result.body).toContain("👌 It's All Good");
    expect(result.body).toContain('Memory usage is below threshold');
    expect(result.body).toContain('[5ms]');
  });

  it('should render fail banner in HTML when a check fails', async () => {
    (dbConnection as jest.Mock).mockResolvedValue({
      componentName: 'db_connection',
      status: Status.fail,
      message: 'Database connection failed',
      value: 'false',
      time: 2,
    });

    const config = buildConfig({
      db_connection: true,
    });

    const result = await healthcheckHandler({ accept: 'text/html' }, config);

    expect(result.type).toBe('text/html');
    expect(result.body).toContain("❌ Something's Wrong");
    expect(result.body).toContain('#F44336');
    expect(result.body).toContain('Database connection failed');
  });

  it('should render warn banner in HTML when a check warns', async () => {
    (disk as jest.Mock).mockResolvedValue({
      componentName: 'disk_space',
      status: Status.warn,
      message: 'Disk space is running low',
      value: '85%',
      time: 4,
    });

    const config = buildConfig({
      disk_space: true,
    });

    const result = await healthcheckHandler({ accept: 'text/html' }, config);

    expect(result.type).toBe('text/html');
    expect(result.body).toContain("❌ Something's Wrong");
    expect(result.body).toContain('#FFC107');
    expect(result.body).toContain('Disk space is running low');
  });

  it('should not display value in HTML when value is "true" or "false"', async () => {
    (cacheConnection as jest.Mock).mockResolvedValue({
      componentName: 'cache_connection',
      status: Status.pass,
      message: 'Cache connection successful',
      value: 'true',
      time: 3,
    });

    const config = buildConfig({
      cache_connection: true,
    });

    const result = await healthcheckHandler({ accept: 'text/html' }, config);

    expect(result.body).toContain('Cache connection successful');
    expect(result.body).not.toContain('(true)');
  });

  it('should display value in HTML when value is not "true" or "false"', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    const config = buildConfig({
      memory_usage: true,
    });

    const result = await healthcheckHandler({ accept: 'text/html' }, config);

    expect(result.body).toContain('(50%)');
  });

  it('should sort results alphabetically by check name in HTML output', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory Message',
      value: '50%',
      time: 5,
    });

    (cpuCheck as jest.Mock).mockResolvedValue({
      componentName: 'cpu_usage',
      status: Status.pass,
      message: 'CPU Message',
      value: '20%',
      time: 3,
    });

    const config = buildConfig({
      memory_usage: true,
      cpu_usage: true,
    });

    const result = await healthcheckHandler({ accept: 'text/html' }, config);

    const cpuIndex = result.body.indexOf('CPU Message');
    const memoryIndex = result.body.indexOf('Memory Message');

    expect(cpuIndex).toBeGreaterThan(-1);
    expect(memoryIndex).toBeGreaterThan(-1);
    expect(cpuIndex).toBeLessThan(memoryIndex);
  });

  it('should return JSON response when Accept header does not include text/html', async () => {
    (memoryCheck as jest.Mock).mockResolvedValue({
      componentName: 'memory_usage',
      status: Status.pass,
      message: 'Memory usage is below threshold',
      value: '50%',
      time: 5,
    });

    const config = buildConfig({
      memory_usage: true,
    });

    const result = await healthcheckHandler({ accept: 'application/json' }, config);

    expect(result.type).toBe('application/json');
    const parsed = JSON.parse(result.body);
    expect(parsed.status).toBe(Status.p