import { healthcheckHandler } from './healthcheck.js';
import { Status } from './index.js';
import { cacheConnection } from './checks/cache.js';
import { cpuCheck } from './checks/cpu.js';
import { dbConnection } from './checks/db.js';
import { disk } from './checks/disk.js';
import { egress } from './checks/egress.js';
import { memoryCheck } from './checks/memory.js';

jest.mock('./checks/cache.js');
jest.mock('./checks/cpu.js');
jest.mock('./checks/db.js');
jest.mock('./checks/disk.js');
jest.mock('./checks/egress.js');
jest.mock('./checks/memory.js');

describe('healthcheckHandler', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('JSON response', () => {
    it('should return JSON response when accept header is not text/html', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below 80%',
        value: '50%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {
        accept: 'application/json',
      };

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      expect(JSON.parse(result.body)).toEqual({
        status: Status.pass,
        description: 'Health check response, generated by allgood.',
        results: {
          memory_usage: mockMemoryResult,
        },
      });
    });

    it('should return JSON response when accept header is undefined', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below 80%',
        value: '50%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {};

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      expect(JSON.parse(result.body)).toEqual({
        status: Status.pass,
        description: 'Health check response, generated by allgood.',
        results: {
          memory_usage: mockMemoryResult,
        },
      });
    });

    it('should return fail status when one check fails', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.fail,
        message: 'Memory usage is above 80%',
        value: '90%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {};

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      const body = JSON.parse(result.body);
      expect(body.status).toBe(Status.fail);
    });

    it('should return warn status when one check warns', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.warn,
        message: 'Memory usage is at warning level',
        value: '75%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {};

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      const body = JSON.parse(result.body);
      expect(body.status).toBe(Status.warn);
    });

    it('should run multiple checks in parallel', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below 80%',
        value: '50%',
        time: 10,
      };

      const mockCpuResult = {
        componentName: 'cpu_usage',
        status: Status.pass,
        message: 'CPU usage is below 80%',
        value: '40%',
        time: 15,
      };

      const mockDiskResult = {
        componentName: 'disk_space',
        status: Status.pass,
        message: 'Disk space is sufficient',
        value: '60%',
        time: 12,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);
      (cpuCheck as jest.Mock).mockResolvedValue(mockCpuResult);
      (disk as jest.Mock).mockResolvedValue(mockDiskResult);

      const headers = {};

      const config = {
        checks: {
          memory_usage: true,
          cpu_usage: true,
          disk_space: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      const body = JSON.parse(result.body);
      expect(body.status).toBe(Status.pass);
      expect(body.results).toEqual({
        memory_usage: mockMemoryResult,
        cpu_usage: mockCpuResult,
        disk_space: mockDiskResult,
      });
      expect(memoryCheck).toHaveBeenCalledWith(config);
      expect(cpuCheck).toHaveBeenCalledWith(config);
      expect(disk).toHaveBeenCalledWith(config);
    });

    it('should only run enabled checks', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below 80%',
        value: '50%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {};

      const config = {
        checks: {
          memory_usage: true,
          cpu_usage: false,
          disk_space: false,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      const body = JSON.parse(result.body);
      expect(body.results).toEqual({
        memory_usage: mockMemoryResult,
      });
      expect(memoryCheck).toHaveBeenCalledWith(config);
      expect(cpuCheck).not.toHaveBeenCalled();
      expect(disk).not.toHaveBeenCalled();
    });

    it('should handle all check types', async () => {
      const mockResults = {
        memory_usage: {
          componentName: 'memory_usage',
          status: Status.pass,
          message: 'Memory OK',
          value: '50%',
          time: 10,
        },
        outbound_internet: {
          componentName: 'outbound_internet',
          status: Status.pass,
          message: 'Internet OK',
          value: 'true',
          time: 20,
        },
        disk_space: {
          componentName: 'disk_space',
          status: Status.pass,
          message: 'Disk OK',
          value: '60%',
          time: 15,
        },
        cache_connection: {
          componentName: 'cache_connection',
          status: Status.pass,
          message: 'Cache OK',
          value: 'true',
          time: 25,
        },
        db_connection: {
          componentName: 'db_connection',
          status: Status.pass,
          message: 'DB OK',
          value: 'true',
          time: 30,
        },
        cpu_usage: {
          componentName: 'cpu_usage',
          status: Status.pass,
          message: 'CPU OK',
          value: '40%',
          time: 12,
        },
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockResults.memory_usage);
      (egress as jest.Mock).mockResolvedValue(mockResults.outbound_internet);
      (disk as jest.Mock).mockResolvedValue(mockResults.disk_space);
      (cacheConnection as jest.Mock).mockResolvedValue(mockResults.cache_connection);
      (dbConnection as jest.Mock).mockResolvedValue(mockResults.db_connection);
      (cpuCheck as jest.Mock).mockResolvedValue(mockResults.cpu_usage);

      const headers = {};

      const config = {
        checks: {
          memory_usage: true,
          outbound_internet: true,
          disk_space: true,
          cache_connection: true,
          db_connection: true,
          cpu_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('application/json');
      const body = JSON.parse(result.body);
      expect(body.results).toEqual(mockResults);
    });
  });

  describe('HTML response', () => {
    it('should return HTML response when accept header includes text/html', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below 80%',
        value: '50%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {
        accept: 'text/html',
      };

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('text/html');
      expect(result.body).toContain('<!DOCTYPE html>');
      expect(result.body).toContain('Health Check');
      expect(result.body).toContain('👌 It\'s All Good');
      expect(result.body).toContain('#4CAF50');
      expect(result.body).toContain('Memory usage is below 80%');
      expect(result.body).toContain('✅');
    });

    it('should return HTML response with fail banner when a check fails', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.fail,
        message: 'Memory usage is above 80%',
        value: '90%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {
        accept: 'text/html,application/xhtml+xml',
      };

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('text/html');
      expect(result.body).toContain('❌ Something\'s Wrong');
      expect(result.body).toContain('#F44336');
      expect(result.body).toContain('Memory usage is above 80%');
      expect(result.body).toContain('❌');
    });

    it('should return HTML response with warn banner when a check warns', async () => {
      const mockMemoryResult = {
        componentName: 'memory_usage',
        status: Status.warn,
        message: 'Memory usage is at warning level',
        value: '75%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockMemoryResult);

      const headers = {
        accept: 'text/html',
      };

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('text/html');
      expect(result.body).toContain('❌ Something\'s Wrong');
      expect(result.body).toContain('#FFC107');
      expect(result.body).toContain('Memory usage is at warning level');
      expect(result.body).toContain('⚠️');
    });

    it('should display multiple checks sorted alphabetically in HTML', async () => {
      const mockResults = {
        disk_space: {
          componentName: 'disk_space',
          status: Status.pass,
          message: 'Disk space OK',
          value: '60%',
          time: 15,
        },
        cpu_usage: {
          componentName: 'cpu_usage',
          status: Status.pass,
          message: 'CPU usage OK',
          value: '40%',
          time: 12,
        },
        memory_usage: {
          componentName: 'memory_usage',
          status: Status.pass,
          message: 'Memory usage OK',
          value: '50%',
          time: 10,
        },
      };

      (disk as jest.Mock).mockResolvedValue(mockResults.disk_space);
      (cpuCheck as jest.Mock).mockResolvedValue(mockResults.cpu_usage);
      (memoryCheck as jest.Mock).mockResolvedValue(mockResults.memory_usage);

      const headers = {
        accept: 'text/html',
      };

      const config = {
        checks: {
          disk_space: true,
          cpu_usage: true,
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('text/html');
      const cpuIndex = result.body.indexOf('CPU usage OK');
      const diskIndex = result.body.indexOf('Disk space OK');
      const memoryIndex = result.body.indexOf('Memory usage OK');
      
      expect(cpuIndex).toBeLessThan(diskIndex);
      expect(diskIndex).toBeLessThan(memoryIndex);
    });

    it('should not display value when it is "true" or "false" in HTML', async () => {
      const mockResult = {
        componentName: 'cache_connection',
        status: Status.pass,
        message: 'Cache connection successful',
        value: 'true',
        time: 25,
      };

      (cacheConnection as jest.Mock).mockResolvedValue(mockResult);

      const headers = {
        accept: 'text/html',
      };

      const config = {
        checks: {
          cache_connection: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('text/html');
      expect(result.body).toContain('Cache connection successful');
      expect(result.body).not.toContain('(true)');
    });

    it('should display value when it is not "true" or "false" in HTML', async () => {
      const mockResult = {
        componentName: 'memory_usage',
        status: Status.pass,
        message: 'Memory usage is below 80%',
        value: '50%',
        time: 10,
      };

      (memoryCheck as jest.Mock).mockResolvedValue(mockResult);

      const headers = {
        accept: 'text/html',
      };

      const config = {
        checks: {
          memory_usage: true,
        },
      };

      const result = await healthcheckHandler(headers, config);

      expect(result.type).toBe('text/html');
      expect(result.body).toContain('Memory usage is below 80%');
      expect(result.body).toContain('(50%)');
    });