import type { Config } from "./index.js";

export const healthcheckHandler = (
  headers: Record<string, string | undefined>,
  config: Config
) => {
  const acceptHeader = headers["accept"];

  if (acceptHeader && acceptHeader.includes("text/html")) {
    // Return the HTML
  } else {
    return {
      type: "application/json",
      body: JSON.stringify({
        status: "",
        description: "Health check response, generated by allgood.",
        // checks: {

        // }
      }),
    };
  }
};
