import { healthcheckHandler } from './healthcheck.js';
import { cacheConnection } from './checks/cache.js';
import { cpuCheck } from './checks/cpu.js';
import { dbConnection } from './checks/db.js';
import { disk } from './checks/disk.js';
import { egress } from './checks/egress.js';
import { memoryCheck } from './checks/memory.js';
import { Status, type Config } from './index.js';

jest.mock('./checks/cache.js', () => ({
  cacheConnection: jest.fn(),
}));

jest.mock('./checks/cpu.js', () => ({
  cpuCheck: jest.fn(),
}));

jest.mock('./checks/db.js', () => ({
  dbConnection: jest.fn(),
}));

jest.mock('./checks/disk.js', () => ({
  disk: jest.fn(),
}));

jest.mock('./checks/egress.js', () => ({
  egress: jest.fn(),
}));

jest.mock('./checks/memory.js', () => ({
  memoryCheck: jest.fn(),
}));

describe('healthcheckHandler', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  const baseConfig = (checks: Partial<Config['checks']>): Config =>
    ({
      checks,
    } as unknown as Config);

  describe('JSON response', () => {
    it('should return a pass status with empty results when no checks are enabled', async () => {
      const config = baseConfig({});

      const result = await healthcheckHandler({}, config);

      expect(result.type).toBe('application/json');
      const body = JSON.parse(result.body);
      expect(body).toEqual({
        status: Status.pass,
        description: 'Health check response, generated by allgood.',
        results: {},
      });
    });

    it('should skip checks that are not enabled (false)', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });

      const config = baseConfig({
        memory_usage: false,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(memoryCheck).not.toHaveBeenCalled();
      expect(body.results).toEqual({});
      expect(body.status).toBe(Status.pass);
    });

    it('should skip check names not present in the registry', async () => {
      const config = baseConfig({
        // @ts-expect-error - testing unknown check name
        unknown_check: true,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(body.results).toEqual({});
      expect(body.status).toBe(Status.pass);
    });

    it('should run all enabled checks and aggregate a pass status', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.pass,
        message: 'Memory usage is fine',
        value: 'true',
        time: 5,
      });

      (egress as jest.Mock).mockResolvedValue({
        componentName: 'outbound_internet',
        status: Status.pass,
        message: 'Outbound internet is fine',
        value: 'true',
        time: 10,
      });

      const config = baseConfig({
        memory_usage: true,
        outbound_internet: true,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(memoryCheck).toHaveBeenCalledWith(config);
      expect(egress).toHaveBeenCalledWith(config);
      expect(body.status).toBe(Status.pass);
      expect(body.results).toEqual({
        memory_usage: {
          componentName: 'memory',
          status: Status.pass,
          message: 'Memory usage is fine',
          value: 'true',
          time: 5,
        },
        outbound_internet: {
          componentName: 'outbound_internet',
          status: Status.pass,
          message: 'Outbound internet is fine',
          value: 'true',
          time: 10,
        },
      });
    });

    it('should set overall status to warn when a check warns', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.warn,
        message: 'Memory usage is high',
        value: '75%',
        time: 5,
      });

      const config = baseConfig({
        memory_usage: true,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(body.status).toBe(Status.warn);
    });

    it('should set overall status to fail when a check fails', async () => {
      (dbConnection as jest.Mock).mockResolvedValue({
        componentName: 'db_connection',
        status: Status.fail,
        message: 'DB connection failed',
        value: 'false',
        time: 2,
      });

      const config = baseConfig({
        db_connection: true,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(body.status).toBe(Status.fail);
    });

    it('should prioritize fail over warn regardless of check order', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.warn,
        message: 'Memory usage is high',
        value: '75%',
        time: 5,
      });

      (dbConnection as jest.Mock).mockResolvedValue({
        componentName: 'db_connection',
        status: Status.fail,
        message: 'DB connection failed',
        value: 'false',
        time: 2,
      });

      const config = baseConfig({
        memory_usage: true,
        db_connection: true,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(body.status).toBe(Status.fail);
    });

    it('should run all check types when enabled', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });
      (egress as jest.Mock).mockResolvedValue({
        componentName: 'outbound_internet',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });
      (disk as jest.Mock).mockResolvedValue({
        componentName: 'disk_space',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });
      (cacheConnection as jest.Mock).mockResolvedValue({
        componentName: 'cache_connection',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });
      (dbConnection as jest.Mock).mockResolvedValue({
        componentName: 'db_connection',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });
      (cpuCheck as jest.Mock).mockResolvedValue({
        componentName: 'cpu_usage',
        status: Status.pass,
        message: 'ok',
        value: 'true',
        time: 1,
      });

      const config = baseConfig({
        memory_usage: true,
        outbound_internet: true,
        disk_space: true,
        cache_connection: true,
        db_connection: true,
        cpu_usage: true,
      });

      const result = await healthcheckHandler({}, config);
      const body = JSON.parse(result.body);

      expect(memoryCheck).toHaveBeenCalled();
      expect(egress).toHaveBeenCalled();
      expect(disk).toHaveBeenCalled();
      expect(cacheConnection).toHaveBeenCalled();
      expect(dbConnection).toHaveBeenCalled();
      expect(cpuCheck).toHaveBeenCalled();
      expect(Object.keys(body.results)).toHaveLength(6);
    });

    it('should default to JSON when accept header is missing', async () => {
      const config = baseConfig({});

      const result = await healthcheckHandler({}, config);

      expect(result.type).toBe('application/json');
    });

    it('should default to JSON when accept header does not include text/html', async () => {
      const config = baseConfig({});

      const result = await healthcheckHandler(
        { accept: 'application/json' },
        config
      );

      expect(result.type).toBe('application/json');
    });
  });

  describe('HTML response', () => {
    it('should return HTML when accept header includes text/html', async () => {
      const config = baseConfig({});

      const result = await healthcheckHandler(
        { accept: 'text/html' },
        config
      );

      expect(result.type).toBe('text/html');
      expect(result.body).toContain('<!DOCTYPE html>');
    });

    it('should render a pass banner when all checks pass', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.pass,
        message: 'Memory usage is fine',
        value: 'true',
        time: 5,
      });

      const config = baseConfig({
        memory_usage: true,
      });

      const result = await healthcheckHandler(
        { accept: 'text/html' },
        config
      );

      expect(result.body).toContain("👌 It's All Good");
      expect(result.body).toContain('#4CAF50');
      expect(result.body).toContain('Memory usage is fine');
      expect(result.body).toContain('✅');
    });

    it('should render a warn banner when a check warns', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.warn,
        message: 'Memory usage is high',
        value: '75%',
        time: 5,
      });

      const config = baseConfig({
        memory_usage: true,
      });

      const result = await healthcheckHandler(
        { accept: 'text/html' },
        config
      );

      expect(result.body).toContain("❌ Something's Wrong");
      expect(result.body).toContain('#FFC107');
      expect(result.body).toContain('⚠️');
    });

    it('should render a fail banner when a check fails', async () => {
      (dbConnection as jest.Mock).mockResolvedValue({
        componentName: 'db_connection',
        status: Status.fail,
        message: 'DB connection failed',
        value: 'false',
        time: 2,
      });

      const config = baseConfig({
        db_connection: true,
      });

      const result = await healthcheckHandler(
        { accept: 'text/html' },
        config
      );

      expect(result.body).toContain("❌ Something's Wrong");
      expect(result.body).toContain('#F44336');
      expect(result.body).toContain('❌');
      expect(result.body).toContain('DB connection failed');
    });

    it('should not show the value for boolean-like true/false values', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.pass,
        message: 'Memory usage is fine',
        value: 'true',
        time: 5,
      });

      const config = baseConfig({
        memory_usage: true,
      });

      const result = await healthcheckHandler(
        { accept: 'text/html' },
        config
      );

      expect(result.body).not.toContain('(true)');
    });

    it('should show the value when it is not "true" or "false"', async () => {
      (memoryCheck as jest.Mock).mockResolvedValue({
        componentName: 'memory',
        status: Status.warn,
        message: 'Memory usage is high',